// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqPr2BQjySxnK-bGzrGagunuJS2PptACk',
    appId: '1:448949942338:web:b233af3174491b1fdb15db',
    messagingSenderId: '448949942338',
    projectId: 'onlinecarmarketplaceapp-f9898',
    authDomain: 'onlinecarmarketplaceapp-f9898.firebaseapp.com',
    storageBucket: 'onlinecarmarketplaceapp-f9898.firebasestorage.app',
    measurementId: 'G-54WC3SMC0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1b_p20vNVTLg7366s2rLuShDGf4zf1pI',
    appId: '1:448949942338:android:21c11df1774f5ad8db15db',
    messagingSenderId: '448949942338',
    projectId: 'onlinecarmarketplaceapp-f9898',
    storageBucket: 'onlinecarmarketplaceapp-f9898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu-urMvSdeWCKq5z1mKCsIdLJyPLFMQGc',
    appId: '1:448949942338:ios:9a0a32cd6f986fb0db15db',
    messagingSenderId: '448949942338',
    projectId: 'onlinecarmarketplaceapp-f9898',
    storageBucket: 'onlinecarmarketplaceapp-f9898.firebasestorage.app',
    iosClientId: '448949942338-21kihljhulqfbaur7g79eabmdcu6l09c.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineCarMarketplaceApp',
  );
}
