name: Flutter CD (Firebase App Distribution)

on:
  push:
    tags:
      - "v*.*.*" # ví dụ: v1.0.0

jobs:
  deploy-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java Environment (Tránh lỗi biên dịch Kotlin/Gradle)
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.8"
          channel: stable
          cache: true

      # 4. Clean project trước khi build release
      - name: Clean Flutter
        run: flutter clean

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Inject Firebase config
      - name: Inject Firebase config
        run: |
          mkdir -p android/app
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json

      # 7. Build APK release
      - name: Build APK (release)
        run: flutter build apk --release

      # 8. Deploy to Firebase App Distribution
      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: frontend/build/app/outputs/flutter-apk/app-release.apk
